name: CI

on:
  pull_request:
  push:
    branches: [ "katie-dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create venv + install deps + verify
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements_freeze_2025-12-10.txt
          chmod +x verify.sh
          ./verify.sh

